+ MAYAVERSION:2020 RadeonProRender 1.0 %FR_MAYA_PLUGIN_DEV_PATH%/dist
PATH+:=bin
MAYA_RENDER_DESC_PATH+:=renderDesc
MAYA_CUSTOM_TEMPLATE_PATH+:=scripts/Templates
XBMLANGPATH+:=icons
MAYA_SHADER_LIBRARY_PATH+:=materials
RPR_SCRIPTS_PATH:=scripts
plug-ins: plug-ins/2020/

+ MAYAVERSION:2022 RadeonProRender 1.0 %FR_MAYA_PLUGIN_DEV_PATH%/dist
PATH+:=bin
MAYA_RENDER_DESC_PATH+:=renderDesc
MAYA_CUSTOM_TEMPLATE_PATH+:=scripts/Templates
XBMLANGPATH+:=icons
MAYA_SHADER_LIBRARY_PATH+:=materials
RPR_SCRIPTS_PATH:=scripts
plug-ins: plug-ins/2022/

+ MAYAVERSION:2023 RadeonProRender 1.0 %FR_MAYA_PLUGIN_DEV_PATH%/dist
PATH+:=bin
MAYA_RENDER_DESC_PATH+:=renderDesc
MAYA_CUSTOM_TEMPLATE_PATH+:=scripts/Templates
XBMLANGPATH+:=icons
MAYA_SHADER_LIBRARY_PATH+:=materials
RPR_SCRIPTS_PATH:=scripts
plug-ins: plug-ins/2023/
