#!/bin/bash

# Copyright 2020 Advanced Micro Devices, Inc
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


echo "Uninstalling Radeon ProRender Maya"

# Remove the module files

rm /Users/Shared/Autodesk/modules/maya/2020/RadeonProRender.module
rm /Users/Shared/Autodesk/modules/maya/2022/RadeonProRender.module
rm /Users/Shared/Autodesk/modules/maya/2023/RadeonProRender.module

# Remove the shelves

localUsers=$( dscl . list /Users UniqueID | awk '$2 >= 501 {print $1}' | grep -v admin )

for userName in $localUsers; do
    echo "Removing shelves for $userName..."
    if [ -d "/Users/$userName/Library/Preferences/Autodesk/maya/2020/prefs/shelves/" ]; then
        rm "/Users/$userName/Library/Preferences/Autodesk/maya/2020/prefs/shelves/shelf_Radeon_ProRender.mel"
    fi
    if [ -d "/Users/$userName/Library/Preferences/Autodesk/maya/2022/prefs/shelves/" ]; then
        rm "/Users/$userName/Library/Preferences/Autodesk/maya/2022/prefs/shelves/shelf_Radeon_ProRender.mel"
    fi
    if [ -d "/Users/$userName/Library/Preferences/Autodesk/maya/2023/prefs/shelves/" ]; then
        rm "/Users/$userName/Library/Preferences/Autodesk/maya/2023/prefs/shelves/shelf_Radeon_ProRender.mel"
    fi
done

osascript <<END
tell me to activate
display dialog "Uninstalled Maya modules and shelves." buttons { "OK" } default button 1
END

