#!/bin/bash

echo "Uninstalling Radeon ProRender Maya"

# Remove the module files

rm /Users/Shared/Autodesk/modules/maya/2017/RadeonProRender.module
rm /Users/Shared/Autodesk/modules/maya/2018/RadeonProRender.module
rm /Users/Shared/Autodesk/modules/maya/2019/RadeonProRender.module

# Remove the shelves

localUsers=$( dscl . list /Users UniqueID | awk '$2 >= 501 {print $1}' | grep -v admin )

for userName in $localUsers; do
    echo "Removing shelves for $userName..."
    if [ -d "/Users/$userName/Library/Preferences/Autodesk/maya/2017/prefs/shelves/" ]; then
        rm "/Users/$userName/Library/Preferences/Autodesk/maya/2017/prefs/shelves/shelf_Radeon_ProRender.mel"
    fi
    if [ -d "/Users/$userName/Library/Preferences/Autodesk/maya/2018/prefs/shelves/" ]; then
        rm "/Users/$userName/Library/Preferences/Autodesk/maya/2018/prefs/shelves/shelf_Radeon_ProRender.mel"
    fi
    if [ -d "/Users/$userName/Library/Preferences/Autodesk/maya/2019/prefs/shelves/" ]; then
        rm "/Users/$userName/Library/Preferences/Autodesk/maya/2019/prefs/shelves/shelf_Radeon_ProRender.mel"
    fi
done

osascript <<END
tell me to activate
display dialog "Uninstalled Maya modules and shelves." buttons { "OK" } default button 1
END

